version: "3.9"
services:
  mongo:
    image: mongo:6
    restart: unless-stopped
    ports: ["27017:27017"]
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand({ ping: 1 })"]
      interval: 10s
      timeout: 5s
      retries: 5

  neo4j:
    image: neo4j:5
    restart: unless-stopped
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/${NEO4J_PASSWORD}
      NEO4J_dbms_security_auth__enabled: "true"
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
    healthcheck:
      test: ["CMD", "bash", "-c", "echo 'RETURN 1' | cypher-shell -u neo4j -p ${NEO4J_PASSWORD} || exit 1"]
      interval: 15s
      timeout: 10s
      retries: 10

  api:
    build: ./server
    depends_on:
      mongo:
        condition: service_healthy
      neo4j:
        condition: service_healthy
    env_file: [.env]
    environment:
      MONGO_URL: mongodb://mongo:27017/mach33
      NEO4J_URI: bolt://neo4j:7687
      NEO4J_USER: neo4j
      NEO4J_PASSWORD: ${NEO4J_PASSWORD}
      PORT: 4000
      VITE_API: http://localhost:4000
    ports: ["4000:4000"]
    restart: unless-stopped
    command: ["node", "dist/index.js"]

  client:
    build: ./client
    depends_on: [api]
    ports: ["5173:5173"]
    environment:
      VITE_API: "http://localhost:4000"
    restart: unless-stopped
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0"]

volumes:
  mongo_data:
  neo4j_data:
  neo4j_logs:
